export const ANIMATIONS_TYPES = ['弹跳', '淡入', '翻转', '旋转', '滑入', '缩放']

export const ANIMATIONS = [
  {
    key: 'bounceIn',
    type: '弹跳',
    name: '弹跳',
    icon: 'icon-anime-bounce'
  },
  {
    key: 'bounceInDown',
    type: '弹跳',
    name: '上方弹跳',
    icon: 'icon-anime-bounce-down',
  },
  {
    key: 'bounceInLeft',
    type: '弹跳',
    name: '左侧弹跳',
    icon: 'icon-anime-bounce-left',
  },
  {
    key: 'bounceInRight',
    type: '弹跳',
    name: '右侧弹跳',
    icon: 'icon-anime-bounce-right',
  },
  {
    key: 'bounceInUp',
    type: '弹跳',
    name: '下方弹跳',
    icon: 'icon-anime-bounce-up',
  },
  {
    key: 'fadeIn',
    type: '淡入',
    name: '淡入',
    icon: 'icon-anime-fade',
  },
  {
    key: 'fadeInDown',
    type: '淡入',
    name: '上方淡入',
    icon: 'icon-anime-fade-down',
  },
  {
    key: 'fadeInLeft',
    type: '淡入',
    name: '左侧淡入',
    icon: 'icon-anime-fade-left',
  },
  {
    key: 'fadeInRight',
    type: '淡入',
    name: '右侧淡入',
    icon: 'icon-anime-fade-right',
  },
  {
    key: 'fadeInUp',
    type: '淡入',
    name: '下方淡入',
    icon: 'icon-anime-fade-up',
  },
  {
    key: 'flipInX',
    type: '翻转',
    name: '水平翻转',
    icon: 'icon-anime-flip-x',
  },
  {
    key: 'flipInY',
    type: '翻转',
    name: '垂直翻转',
    icon: 'icon-anime-flip-y',
  },
  {
    key: 'rotateIn',
    type: '旋转',
    name: '旋转',
    icon: 'icon-anime-rotate',
  },
  {
    key: 'rotateInDownLeft',
    type: '旋转',
    name: '左下旋转',
    icon: 'icon-anime-rotate-up-right',
  },
  {
    key: 'rotateInDownRight',
    type: '旋转',
    name: '右下旋转',
    icon: 'icon-anime-rotate-up-left',
  },
  {
    key: 'rotateInUpLeft',
    type: '旋转',
    name: '左上旋转',
    icon: 'icon-anime-rotate-down-right',
  },
  {
    key: 'rotateInUpRight',
    type: '旋转',
    name: '右上旋转',
    icon: 'icon-anime-rotate-down-left',
  },
  {
    key: 'slideInDown',
    type: '滑入',
    name: '上方滑入',
    icon: 'icon-anime-slide-down',
  },
  {
    key: 'slideInLeft',
    type: '滑入',
    name: '左侧滑入',
    icon: 'icon-anime-slide-left',
  },
  {
    key: 'slideInRight',
    type: '滑入',
    name: '右侧滑入',
    icon: 'icon-anime-slide-right',
  },
  {
    key: 'slideInUp',
    type: '滑入',
    name: '下方滑入',
    icon: 'icon-anime-slide-up',
  },
  {
    key: 'zoomIn',
    type: '缩放',
    name: '放大',
    icon: 'icon-anime-zoom',
  },
  {
    key: 'zoomInDown',
    type: '缩放',
    name: '上方放大',
    icon: 'icon-anime-zoom-down',
  },
  {
    key: 'zoomInLeft',
    type: '缩放',
    name: '左侧放大',
    icon: 'icon-anime-zoom-left',
  },
  {
    key: 'zoomInRight',
    type: '缩放',
    name: '右侧放大',
    icon: 'icon-anime-zoom-right',
  },
  {
    key: 'zoomInUp',
    type: '缩放',
    name: '下方放大',
    icon: 'icon-anime-zoom-up',
  },
]