export const ANIMATIONS_TYPES = ['弹跳', '淡入', '翻转', '旋转', '滑入', '缩放']

export const ANIMATIONS = [
  {
    key: 'bounceIn',
    type: '弹跳',
    name: '弹跳',
    icon: 'icon-anime-bounce'
  },
  {
    key: 'bounceInDown',
    type: '弹跳',
    name: '向下弹跳',
    icon: 'icon-anime-bounce-down',
  },
  {
    key: 'bounceInLeft',
    type: '弹跳',
    name: '从左弹跳',
    icon: 'icon-anime-bounce-left',
  },
  {
    key: 'bounceInRight',
    type: '弹跳',
    name: '从右弹跳',
    icon: 'icon-anime-bounce-right',
  },
  {
    key: 'bounceInUp',
    type: '弹跳',
    name: '向上弹跳',
    icon: 'icon-anime-bounce-up',
  },
  {
    key: 'fadeIn',
    type: '淡入',
    name: '淡入',
    icon: 'icon-anime-fade',
  },
  {
    key: 'fadeInDown',
    type: '淡入',
    name: '向下淡入',
    icon: 'icon-anime-fade-down',
  },
  {
    key: 'fadeInLeft',
    type: '淡入',
    name: '从左淡入',
    icon: 'icon-anime-fade-left',
  },
  {
    key: 'fadeInRight',
    type: '淡入',
    name: '从右淡入',
    icon: 'icon-anime-fade-right',
  },
  {
    key: 'fadeInUp',
    type: '淡入',
    name: '向上淡入',
    icon: 'icon-anime-fade-up',
  },
  {
    key: 'flipInX',
    type: '翻转',
    name: '水平翻转',
    icon: 'icon-anime-flip-x',
  },
  {
    key: 'flipInY',
    type: '翻转',
    name: '垂直翻转',
    icon: 'icon-anime-flip-y',
  },
  {
    key: 'rotateIn',
    type: '旋转',
    name: '旋转',
    icon: 'icon-anime-rotate',
  },
  {
    key: 'rotateInDownLeft',
    type: '旋转',
    name: '从左下旋转',
    icon: 'icon-anime-rotate-up-right',
  },
  {
    key: 'rotateInDownRight',
    type: '旋转',
    name: '从右下旋转',
    icon: 'icon-anime-rotate-up-left',
  },
  {
    key: 'rotateInUpLeft',
    type: '旋转',
    name: '从左上旋转',
    icon: 'icon-anime-rotate-down-right',
  },
  {
    key: 'rotateInUpRight',
    type: '旋转',
    name: '从右上旋转',
    icon: 'icon-anime-rotate-down-left',
  },
  {
    key: 'slideInDown',
    type: '滑入',
    name: '向下滑入',
    icon: 'icon-anime-slide-down',
  },
  {
    key: 'slideInLeft',
    type: '滑入',
    name: '从左滑入',
    icon: 'icon-anime-slide-left',
  },
  {
    key: 'slideInRight',
    type: '滑入',
    name: '从右滑入',
    icon: 'icon-anime-slide-right',
  },
  {
    key: 'slideInUp',
    type: '滑入',
    name: '向上滑入',
    icon: 'icon-anime-slide-up',
  },
  {
    key: 'zoomIn',
    type: '缩放',
    name: '放大',
    icon: 'icon-anime-zoom',
  },
  {
    key: 'zoomInDown',
    type: '缩放',
    name: '向下放大',
    icon: 'icon-anime-zoom-down',
  },
  {
    key: 'zoomInLeft',
    type: '缩放',
    name: '从左放大',
    icon: 'icon-anime-zoom-left',
  },
  {
    key: 'zoomInRight',
    type: '缩放',
    name: '从右放大',
    icon: 'icon-anime-zoom-right',
  },
  {
    key: 'zoomInUp',
    type: '缩放',
    name: '向上放大',
    icon: 'icon-anime-zoom-up',
  },
]