export const FONTS = [
  { label: "Default", value: "" },
  { label: "SourceHanSans", value: "SourceHanSans" },
  { label: "SourceHanSerif", value: "SourceHanSerif" },
  { label: "FangZhengHeiTi", value: "FangZhengHeiTi" },
  { label: "FangZhengKaiTi", value: "FangZhengKaiTi" },
  { label: "FangZhengShuSong", value: "FangZhengShuSong" },
  { label: "FangZhengFangSong", value: "FangZhengFangSong" },
  { label: "AlibabaPuHuiTi", value: "AlibabaPuHuiTi" },
  { label: "ZhuqueFangSong", value: "ZhuqueFangSong" },
  { label: "LXGWWenKai", value: "LXGWWenKai" },
  { label: "WenDingPLKaiTi", value: "WenDingPLKaiTi" },
  { label: "DeYiHei", value: "DeYiHei" },
  { label: "MiSans", value: "MiSans" },
  { label: "CangerXiaowanzi", value: "CangerXiaowanzi" },
  { label: "YousheTitleBlack", value: "YousheTitleBlack" },
  { label: "FengguangMingrui", value: "FengguangMingrui" },
  { label: "ShetuModernSquare", value: "ShetuModernSquare" },
  { label: "ZcoolHappy", value: "ZcoolHappy" },
  { label: "ZizhiQuXiMai", value: "ZizhiQuXiMai" },
  { label: "SucaiJishiKangkang", value: "SucaiJishiKangkang" },
  { label: "SucaiJishiCoolSquare", value: "SucaiJishiCoolSquare" },
  { label: "TuniuRounded", value: "TuniuRounded" },
  { label: "RuiziZhenyan", value: "RuiziZhenyan" },
];
