export const SYS_FONTS = [
  { zh: '微软雅黑', en: 'Microsoft Yahei' },
  { zh: '宋体', en: 'SimSun' },
  { zh: '黑体', en: 'SimHei' },
  { zh: '楷体', en: 'KaiTi' },
  { zh: '新宋体', en: 'NSimSun' },
  { zh: '仿宋', en: 'FangSong' },
  { zh: '苹方', en: 'PingFang SC' },
  { zh: '华文黑体', en: 'STHeiti' },
  { zh: '华文楷体', en: 'STKaiti' },
  { zh: '华文宋体', en: 'STSong' },
  { zh: '华文仿宋', en: 'STFangSong' },
  { zh: '华文中宋', en: 'STZhongSong' },
  { zh: '华文琥珀', en: 'STHupo' },
  { zh: '华文新魏', en: 'STXinwei' },
  { zh: '华文隶书', en: 'STLiti' },
  { zh: '华文行楷', en: 'STXingkai' },
  { zh: '冬青黑体简', en: 'Hiragino Sans GB' },
  { zh: '兰亭黑-简', en: 'Lantinghei SC' },
  { zh: '偏偏体-简', en: 'Hanzipen SC' },
  { zh: '手札体-简', en: 'Hannotate SC' },
  { zh: '宋体-简', en: 'Songti SC' },
  { zh: '娃娃体-简', en: 'Wawati SC' },
  { zh: '行楷-简', en: 'Xingkai SC' },
  { zh: '圆体-简', en: 'Yuanti SC' },
  { zh: '华文细黑', en: 'STXihei' },
  { zh: '幼圆', en: 'YouYuan' },
  { zh: '隶书', en: 'LiSu' },
  { zh: 'Arial', en: 'Arial' },
]

export const WEB_FONTS = [
  { name: '仓耳小丸子' },
  { name: '优设标题黑' },
  { name: '峰广明锐体' },
  { name: '摄图摩登小方体' },
  { name: '站酷快乐体' },
  { name: '站酷酷黑体' },
  { name: '素材集市康康体' },
  { name: '联盟起艺卢帅正锐黑体' },
  { name: '谦度手写楷体' },
  { name: '途牛类圆体' },
  { name: '锐字真言体' },
  { name: '问藏书房' },
]