import { t } from '@/i18n';

export const FONTS = [
  { label: t('Commons.label.text_km5960'), value: '' },
  { label: t('Commons.label.text_cldc6t'), value: 'SourceHanSans' },
  { label: t('Commons.label.text_cl1w8r'), value: 'SourceHanSerif' },
  { label: t('Commons.label.pl'), value: 'WenDingPLKaiTi' },
  { label: t('Commons.label.pl_2'), value: 'WenDingPLSongTi' },
  { label: t('Commons.label.text_dn0qqj'), value: 'ZhuqueFangSong' },
  { label: t('Commons.label.text_jputzi'), value: 'LXGWWenKai' },
  { label: t('Commons.label.text_3zymxg'), value: 'AlibabaPuHuiTi' },
  { label: 'MiSans', value: 'MiSans' },
  { label: t('Commons.label.text_ehf95'), value: 'DeYiHei' },
  { label: t('Commons.label.text_uecxnd'), value: 'CangerXiaowanzi' },
  { label: t('Commons.label.text_rtw5pi'), value: 'YousheTitleBlack' },
  { label: t('Commons.label.text_kkz8bm'), value: 'FengguangMingrui' },
  { label: t('Commons.label.text_ceqkrh'), value: 'ShetuModernSquare' },
  { label: t('Commons.label.text_1v2ugg'), value: 'ZcoolHappy' },
  { label: t('Commons.label.text_wfjx2t'), value: 'ZizhiQuXiMai' },
  { label: t('Commons.label.text_ed78s9'), value: 'SucaiJishiKangkang' },
  { label: t('Commons.label.text_e5qg57'), value: 'SucaiJishiCoolSquare' },
  { label: t('Commons.label.text_a1bh5t'), value: 'TuniuRounded' },
  { label: t('Commons.label.text_qlv6dn'), value: 'RuiziZhenyan' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: t('Commons.label.jetbrains_mono'), value: 'JetBrainsMono' },
  { label: t('Commons.label.literata'), value: 'Literata' },
  { label: t('Commons.label.inter'), value: 'Inter' },
  { label: t('Commons.label.roboto'), value: 'Roboto' },
  { label: t('Commons.label.open_sans'), value: 'OpenSans' },
  { label: t('Commons.label.montserrat'), value: 'Montserrat' },
  { label: t('Configs.Font.label.source_sans_pro'), value: 'SourceSansPro' },
  { label: t('Commons.label.merriweather'), value: 'Merriweather' },
]