export const FONT_FAMILYS = [
  { source: 'windows', zh: '微软雅黑', en: 'Microsoft Yahei' },
  { source: 'windows', zh: '宋体', en: 'SimSun' },
  { source: 'windows', zh: '黑体', en: 'SimHei' },
  { source: 'windows', zh: '楷体', en: 'KaiTi' },
  { source: 'windows', zh: '新宋体', en: 'NSimSun' },
  { source: 'windows', zh: '仿宋', en: 'FangSong' },

  { source: 'osx', zh: '苹方', en: 'PingFang SC' },
  { source: 'osx', zh: '华文黑体', en: 'STHeiti' },
  { source: 'osx', zh: '华文楷体', en: 'STKaiti' },
  { source: 'osx', zh: '华文宋体', en: 'STSong' },
  { source: 'osx', zh: '华文仿宋', en: 'STFangSong' },
  { source: 'osx', zh: '华文中宋', en: 'STZhongSong' },
  { source: 'osx', zh: '华文琥珀', en: 'STHupo' },
  { source: 'osx', zh: '华文新魏', en: 'STXinwei' },
  { source: 'osx', zh: '华文隶书', en: 'STLiti' },
  { source: 'osx', zh: '华文行楷', en: 'STXingkai' },
  { source: 'osx', zh: '冬青黑体简', en: 'Hiragino Sans GB' },
  { source: 'osx', zh: '兰亭黑-简', en: 'Lantinghei SC' },
  { source: 'osx', zh: '偏偏体-简', en: 'Hanzipen SC' },
  { source: 'osx', zh: '手札体-简', en: 'Hannotate SC' },
  { source: 'osx', zh: '宋体-简', en: 'Songti SC' },
  { source: 'osx', zh: '娃娃体-简', en: 'Wawati SC' },
  { source: 'osx', zh: '行楷-简', en: 'Xingkai SC' },
  { source: 'osx', zh: '圆体-简', en: 'Yuanti SC' },
  
  { source: 'office', zh: '华文细黑', en: 'STXihei' },
  { source: 'office', zh: '幼圆', en: 'YouYuan' },
  { source: 'office', zh: '隶书', en: 'LiSu' },
  { source: '', zh: 'Arial', en: 'Arial' },
]